import { Karla } from "next/font/google";
import Nav from "./components/Nav";
import "./globals.css";

const inter = Karla({ subsets: ["latin"] });

export const metadata = {
  title: "MyPage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " relative text-white"}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
